title: "Complex Trait Genetics Zan Lab"
author: "Zan Lab"
description: "Swedish University of Agriculture Sciences"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: Home }
  - {file: "README.md",title: Members}
  - {file: "CV_yanjunzan.pdf",title: Research }
  - {file: "CV_yanjunzan.pdf",title: Publications}
  - {file: "CV_yanjunzan.pdf",title: Resources}
  - {file: "CV_yanjunzan.pdf",title: Philosophy}
  - {file: "CV_yanjunzan.pdf",title: Opportunities}
  - {file: "CV_yanjunzan.pdf",title: Contact Us}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:yanjun_zan@aliyun.com"}
  - {title: Github, icon: github, url: "https://yanjunzan@github.io"}
  - {title: Bilibili, icon: rss, url: "https://space.bilibili.com/629646873"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
